# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
language: "ruby"

before_install:
  - gem install bundler
script: "bundle exec rake --trace"

rvm:
  - 2.3.0
  - 2.4.1
  - 2.5.3

matrix:
  include:
    - name: JRuby 9.1
      rvm: jruby-9.1.17.0
      jdk: openjdk8
    - name: JRuby 9.2
      rvm: jruby-9.2.11.1
      jdk: openjdk11
      env: JAVA_OPTS="--add-opens java.base/java.security.cert=ALL-UNNAMED --add-opens java.base/java.security=ALL-UNNAMED"
    - name: Rubinius
      rvm: rbx-4
      dist: trusty
  allow_failures:
    - name: Rubinius
    - name: JRuby 9.2
  fast_finish: true

notifications:
  irc: "irc.freenode.org#savon"
