# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options
language: "ruby"

before_install:
  - gem install bundler
script: "bundle exec rake --trace"

rvm:
  - 2.3.0
  - 2.4.1
  - 2.5.3
  - rbx-4

matrix:
  include:
    - rvm: jruby-9.1.17.0
      jdk: openjdk8
    - rvm: jruby-9.2.11.1
      jdk: openjdk11
  allow_failures:
    - rvm: rbx-4
  fast_finish: true

notifications:
  irc: "irc.freenode.org#savon"
